### ISSUE TITLE
Fix link to helm layer

### ISSUE THREAD

**Issue by riwim** [syl20bnr/spacemacs.org#16]
I get a 404 for the link to the helm layer on http://spacemacs.org/layers/LAYERS.html :
http://spacemacs.org/layers/+completion/helm/README.html

**Comment by duianto** [comment]
I checked the rest of the links and these lead to 404 pages.

### 3 Completion
helm
http://develop.spacemacs.org/layers/+completion/helm/README.html

ivy
http://develop.spacemacs.org/layers/+completion/ivy/README.html

### Issue:
There's no "+completion" folder in: https://github.com/syl20bnr/develop.spacemacs.org/tree/gh-pages/layers

There's only a "+completion/auto-completion" folder that contains the README.html file, for the "Auto-completion layer" page: http://spacemacs.org/layers/+completion/auto-completion/README.html


### 4 Distributions
spacemacs
http://develop.spacemacs.org/layers/+distributions/spacemacs/README.html

spacemacs-base
http://develop.spacemacs.org/layers/+distributions/spacemacs-base/README.html

spacemacs-bootstrap
http://develop.spacemacs.org/layers/+distributions/spacemacs-bootstrap/README.html

### Issue:
There's no "+distributions" folder in: https://github.com/syl20bnr/develop.spacemacs.org/tree/gh-pages/layers

### 11 Misc
nlinum
http://develop.spacemacs.org/layers/+misc/nlinum/README.html

### Issue:
There's no "+misc" folder in: https://github.com/syl20bnr/develop.spacemacs.org/tree/gh-pages/layers

### 15 Spacemacs distribution layers
spacemacs-completion
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-completion/README.html

spacemacs-editing
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-editing/README.html

spacemacs-editing-visual
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-editing-visual/README.html

spacemacs-evil
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-evil/README.html

spacemacs-language
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-language/README.html

spacemacs-layouts
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-layouts/README.html

spacemacs-misc
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-misc/README.html

spacemacs-org
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-org/README.html

spacemacs-ui
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-ui/README.html

spacemacs-ui-visual
http://develop.spacemacs.org/layers/+spacemacs/spacemacs-ui-visual/README.html

### Issue:
There's no "+spacemacs" folder in: https://github.com/syl20bnr/develop.spacemacs.org/tree/gh-pages/layers  

#### Notes:
I checked the http://develop.spacemacs.org/layers/LAYERS.html links, i assume that it's the most up to date version, but just in case, i also checked a handful of the http://spacemacs.org/layers/LAYERS.html (non-develop) links, and both pages seem to have the same broken links, for the same reasons.

**Comment by syl20bnr** [comment]
Thank you for the report.
Fixed in `develop.spacemacs.org` will be merged to `spacemacs.org` at next major release.

**Comment by morgajel** [comment]
Not positive, but this looks like it's still an issue- Every doc page I opened is a 404. Any chance this was an oversight, or has a major releast not been dropped in the past year? (sorry, I'm new to spacemacs as of about 12 hours ago).

**Comment by nashamri** [comment]
Most of these are fixed on the develop branch, just waiting for a new
release. You can check that here http://develop.spacemacs.org

**Comment by n-hebert** [comment]
Hello! I'm reading about Spacemacs and these links are still broken on the main `https://www.spacemacs.org/layers/LAYERS.html` site, is it worth cutting a release to fix the docs, since it's been a few years since this thread was last updated?
